EXPLAIN SELECT env, time_bin, AVG(max_bin_val)
FROM
  (
    SELECT  f_dkey,
            date_bin(INTERVAL '30 seconds', timestamp) AS time_bin,
            MAX(env) AS env,
            MAX(value) AS max_bin_val
    FROM
    (
        SELECT f.f_dkey, f.timestamp, d.env, f.value
        FROM
            (SELECT DISTINCT d_dkey, env
            FROM   dim2_parquet
            WHERE  service = 'log'
            ) AS d,
            fact_parquet_sorted AS f
        WHERE d.d_dkey = f.f_dkey
    ) AS j
    GROUP BY f_dkey, time_bin
  ) AS a
GROUP BY env, time_bin
ORDER BY env, time_bin;
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Sort: a.env ASC NULLS LAST, a.time_bin ASC NULLS LAST                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|               |   Aggregate: groupBy=[[a.env, a.time_bin]], aggr=[[avg(a.max_bin_val)]]                                                                                                                                                                                                                                                                                                                                                                                                                    |
|               |     SubqueryAlias: a                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|               |       Projection: date_bin(IntervalMonthDayNano("IntervalMonthDayNano { months: 0, days: 0, nanoseconds: 30000000000 }"),j.timestamp) AS time_bin, max(j.env) AS env, max(j.value) AS max_bin_val                                                                                                                                                                                                                                                                                          |
|               |         Aggregate: groupBy=[[j.f_dkey, date_bin(IntervalMonthDayNano("IntervalMonthDayNano { months: 0, days: 0, nanoseconds: 30000000000 }"), j.timestamp)]], aggr=[[max(j.env), max(j.value)]]                                                                                                                                                                                                                                                                                           |
|               |           SubqueryAlias: j                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               |             Projection: f.f_dkey, f.timestamp, d.env, f.value                                                                                                                                                                                                                                                                                                                                                                                                                              |
|               |               Inner Join: d.d_dkey = f.f_dkey                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|               |                 SubqueryAlias: d                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|               |                   Aggregate: groupBy=[[dim2_parquet.d_dkey, dim2_parquet.env]], aggr=[[]]                                                                                                                                                                                                                                                                                                                                                                                                  |
|               |                     Projection: dim2_parquet.d_dkey, dim2_parquet.env                                                                                                                                                                                                                                                                                                                                                                                                                      |
|               |                       Filter: dim2_parquet.service = Utf8View("log")                                                                                                                                                                                                                                                                                                                                                                                                                       |
|               |                         TableScan: dim2_parquet projection=[d_dkey, env, service], partial_filters=[dim2_parquet.service = Utf8View("log")]                                                                                                                                                                                                                                                                                                                                                |
|               |                 SubqueryAlias: f                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|               |                   TableScan: fact_parquet_sorted projection=[f_dkey, timestamp, value]                                                                                                                                                                                                                                                                                                                                                                                                     |
| physical_plan | SortExec: expr=[env@0 ASC NULLS LAST, time_bin@1 ASC NULLS LAST], preserve_partitioning=[false]                                                                                                                                                                                                                                                                                                                                                                                            |
|               |   AggregateExec: mode=Single, gby=[env@1 as env, time_bin@0 as time_bin], aggr=[avg(a.max_bin_val)]                                                                                                                                                                                                                                                                                                                                                                                        |
|               |     ProjectionExec: expr=[date_bin(IntervalMonthDayNano("IntervalMonthDayNano { months: 0, days: 0, nanoseconds: 30000000000 }"),j.timestamp)@1 as time_bin, max(j.env)@2 as env, max(j.value)@3 as max_bin_val]                                                                                                                                                                                                                                                                           |
|               |       AggregateExec: mode=Final, gby=[f_dkey@0 as f_dkey, date_bin(IntervalMonthDayNano("IntervalMonthDayNano { months: 0, days: 0, nanoseconds: 30000000000 }"),j.timestamp)@1 as date_bin(IntervalMonthDayNano("IntervalMonthDayNano { months: 0, days: 0, nanoseconds: 30000000000 }"),j.timestamp)], aggr=[max(j.env), max(j.value)], ordering_mode=Sorted                                                                                                                             |
|               |         SortPreservingMergeExec: [f_dkey@0 ASC NULLS LAST, date_bin(IntervalMonthDayNano("IntervalMonthDayNano { months: 0, days: 0, nanoseconds: 30000000000 }"),j.timestamp)@1 ASC NULLS LAST]                                                                                                                                                                                                                                                                                           |
|               |           AggregateExec: mode=Partial, gby=[f_dkey@0 as f_dkey, date_bin(IntervalMonthDayNano { months: 0, days: 0, nanoseconds: 30000000000 }, timestamp@1) as date_bin(IntervalMonthDayNano("IntervalMonthDayNano { months: 0, days: 0, nanoseconds: 30000000000 }"),j.timestamp)], aggr=[max(j.env), max(j.value)], ordering_mode=Sorted                                                                                                                                                |
|               |             ProjectionExec: expr=[f_dkey@1 as f_dkey, timestamp@2 as timestamp, env@0 as env, value@3 as value]                                                                                                                                                                                                                                                                                                                                                                            |
|               |               CoalesceBatchesExec: target_batch_size=8192                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|               |                 HashJoinExec: mode=CollectLeft, join_type=Inner, on=[(d_dkey@0, f_dkey@0)], projection=[env@1, f_dkey@2, timestamp@3, value@4]                                                                                                                                                                                                                                                                                                                                             |
|               |                   AggregateExec: mode=Final, gby=[d_dkey@0 as d_dkey, env@1 as env], aggr=[]                                                                                                                                                                                                                                                                                                                                                                                               |
|               |                     CoalescePartitionsExec                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|               |                       AggregateExec: mode=Partial, gby=[d_dkey@0 as d_dkey, env@1 as env], aggr=[]                                                                                                                                                                                                                                                                                                                                                                                         |
|               |                         CoalesceBatchesExec: target_batch_size=8192                                                                                                                                                                                                                                                                                                                                                                                                                        |
|               |                           FilterExec: service@2 = log, projection=[d_dkey@0, env@1]                                                                                                                                                                                                                                                                                                                                                                                                        |
|               |                             DataSourceExec: file_groups={2 groups: [[d1.parquet], [d2.parquet]]}, projection=[d_dkey, env, service], file_type=parquet, predicate=service@2 = log, pruning_predicate=service_null_count@2 != row_count@3 AND service_min@0 <= log AND log <= service_max@1, required_guarantees=[service in (log)] |
|               |                   DataSourceExec: file_groups={3 groups: [[f1.parquet, f4.parquet, f5.parquet, f6.parquet, f7.parquet, f8.parquet], [f2.parquet], [f3.parquet, f9.parquet, f10.parquet]]}, projection=[f_dkey, timestamp, value], output_ordering=[f_dkey@0 ASC NULLS LAST, timestamp@1 ASC NULLS LAST], file_type=parquet, predicate=DynamicFilter [ empty ]             |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
