EXPLAIN SELECT DISTINCT * from  dim2_parquet_sorted;
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                                                                                                                                                                                          |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Aggregate: groupBy=[[dim2_parquet_sorted.d_dkey, dim2_parquet_sorted.env, dim2_parquet_sorted.service, dim2_parquet_sorted.host]], aggr=[[]]                                                                                                                                                                                                                                                  |
|               |   TableScan: dim2_parquet_sorted projection=[d_dkey, env, service, host]                                                                                                                                                                                                                                                                                                                      |
| physical_plan | AggregateExec: mode=FinalPartitioned, gby=[d_dkey@0 as d_dkey, env@1 as env, service@2 as service, host@3 as host], aggr=[], ordering_mode=PartiallySorted([1, 2, 3])                                                                                                                                                                                                                         |
|               |   SortExec: expr=[env@1 ASC NULLS LAST, service@2 ASC NULLS LAST, host@3 ASC NULLS LAST], preserve_partitioning=[true]                                                                                                                                                                                                                                                                        |
|               |     CoalesceBatchesExec: target_batch_size=8192                                                                                                                                                                                                                                                                                                                                               |
|               |       RepartitionExec: partitioning=Hash([d_dkey@0, env@1, service@2, host@3], 16), input_partitions=16                                                                                                                                                                                                                                                                                       |
|               |         RepartitionExec: partitioning=RoundRobinBatch(16), input_partitions=2                                                                                                                                                                                                                                                                                                                 |
|               |           AggregateExec: mode=Partial, gby=[d_dkey@0 as d_dkey, env@1 as env, service@2 as service, host@3 as host], aggr=[], ordering_mode=PartiallySorted([1, 2, 3])                                                                                                                                                                                                                        |
|               |             DataSourceExec: file_groups={2 groups: [[d1.parquet], [d2.parquet]]}, projection=[d_dkey, env, service, host], output_ordering=[env@1 ASC NULLS LAST, service@2 ASC NULLS LAST, host@3 ASC NULLS LAST], file_type=parquet |
|               |                                                                                                                                                                                                                                                                                                                                                                                               |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
