set datafusion.optimizer.repartition_aggregations=false;

EXPLAIN SELECT DISTINCT * from  dim2_parquet_sorted;
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Aggregate: groupBy=[[dim2_parquet_sorted.d_dkey, dim2_parquet_sorted.env, dim2_parquet_sorted.service, dim2_parquet_sorted.host]], aggr=[[]]                                                                                                                                                                                                                                            |
|               |   TableScan: dim2_parquet_sorted projection=[d_dkey, env, service, host]                                                                                                                                                                                                                                                                                                                |
| physical_plan | AggregateExec: mode=Final, gby=[d_dkey@0 as d_dkey, env@1 as env, service@2 as service, host@3 as host], aggr=[], ordering_mode=PartiallySorted([1, 2, 3])                                                                                                                                                                                                                              |
|               |   SortPreservingMergeExec: [env@1 ASC NULLS LAST, service@2 ASC NULLS LAST, host@3 ASC NULLS LAST]                                                                                                                                                                                                                                                                                      |
|               |     AggregateExec: mode=Partial, gby=[d_dkey@0 as d_dkey, env@1 as env, service@2 as service, host@3 as host], aggr=[], ordering_mode=PartiallySorted([1, 2, 3])                                                                                                                                                                                                                        |
|               |       DataSourceExec: file_groups={2 groups: [[d1.parquet], [d2.parquet]]}, projection=[d_dkey, env, service, host], output_ordering=[env@1 ASC NULLS LAST, service@2 ASC NULLS LAST, host@3 ASC NULLS LAST], file_type=parquet |
|               |                                                                                                                                                                                                                                                                                                                                                                                         |
+---------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
