┌───── DistributedExec
│ CoalescePartitionsExec
│   [Stage 2] => NetworkCoalesceExec: output_partitions=12, input_tasks=3
└──────────────────────────────────────────────────
  ┌───── Stage 2 ── tasks=3, partitions=12
  │ ProjectionExec: expr=[date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@0 as time_bin, count(Int64(1))@1 as count]
  │   DistributedUnionExec: t0:[c0] t1:[c1(0/2)] t2:[c1(1/2)]
  │     AggregateExec: mode=SinglePartitioned, gby=[date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@0 as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)], aggr=[count(Int64(1))]
  │       ProjectionExec: expr=[date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@5 as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)]
  │         AggregateExec: mode=FinalPartitioned, gby=[@application@0 as @application, @device@1 as @device, @region@2 as @region, @station@3 as @station, @fleet@4 as @fleet, date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@5 as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)], aggr=[]
  │           RepartitionExec: partitioning=Hash([date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@5], 4), input_partitions=_
  │             AggregateExec: mode=Partial, gby=[@application@0 as @application, @device@1 as @device, @region@2 as @region, @station@3 as @station, @fleet@4 as @fleet, date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@5 as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)], aggr=[]
  │               ResourceGuardExec(fanout[enforce]>=1000x@10000000rows, build[enforce]>=32.0GiB after 20s): HashJoinExec: mode=Partitioned, join_type=Inner, on=[(key@0, key@0)], projection=[@application@1, @device@2, @region@3, @station@4, @fleet@5, date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@7]
  │                 ConcurrentFileScanExec: file_groups={4 groups: [[fixtures/sensors/window-1/shard-1/metadata-001.meta:0..37462], [fixtures/sensors/window-1/shard-2/metadata-002.meta:0..38902], [], []]}, projection=[key, @application, @device, @region, @station, @fleet], file_type=metadata, output_partitioning=Hash([Column { name: "key", index: 0 }], 4), max_parallel_files_per_partition=10
  │                 BufferExec: capacity=_
  │                   AggregateExec: mode=SinglePartitioned, gby=[key@0 as key, date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@1 as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)], aggr=[], ordering_mode=Sorted
  │                     ProjectionExec: expr=[key@0 as key, date_bin(IntervalMonthDayNano { months: 0, days: 0, nanoseconds: 300000000000 }, timestamp@1) as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)]
  │                       ConcurrentFileScanExec: file_groups={4 groups: [[fixtures/sensors/window-1/shard-1/measurements-003.readings:0..2397, fixtures/sensors/window-1/shard-1/measurements-004.readings:0..1978, fixtures/sensors/window-1/shard-1/measurements-005.readings:0..1788], [fixtures/sensors/window-1/shard-2/measurements-006.readings:0..2055, fixtures/sensors/window-1/shard-2/measurements-007.readings:0..2634, fixtures/sensors/window-1/shard-2/measurements-008.readings:0..2735], [], []]}, projection=[key, timestamp], output_ordering=[key@0 ASC, timestamp@1 ASC], file_type=measurements, output_partitioning=Hash([Column { name: "key", index: 0 }], 4), max_parallel_files_per_partition=10
  │     AggregateExec: mode=SinglePartitioned, gby=[date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@0 as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)], aggr=[count(Int64(1))]
  │       ProjectionExec: expr=[date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@5 as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)]
  │         AggregateExec: mode=FinalPartitioned, gby=[@application@0 as @application, @device@1 as @device, @region@2 as @region, @station@3 as @station, @fleet@4 as @fleet, date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@5 as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)], aggr=[]
  │           [Stage 1] => NetworkShuffleExec: output_partitions=4, input_tasks=3
  └──────────────────────────────────────────────────
    ┌───── Stage 1 ── tasks=3, partitions=8
    │ RepartitionExec: partitioning=Hash([date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@5], 8), input_partitions=_
    │   AggregateExec: mode=Partial, gby=[@application@0 as @application, @device@1 as @device, @region@2 as @region, @station@3 as @station, @fleet@4 as @fleet, date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@5 as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)], aggr=[]
    │     ResourceGuardExec(fanout[enforce]>=1000x@10000000rows, build[enforce]>=32.0GiB after 20s): HashJoinExec: mode=Partitioned, join_type=Inner, on=[(key@0, key@0)], projection=[@application@1, @device@2, @region@3, @station@4, @fleet@5, date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@7]
    │       DistributedLeafExec:
    │         t0: ConcurrentFileScanExec: file_groups={4 groups: [[fixtures/sensors/window-2/shard-1/metadata-009.meta:0..37462], [fixtures/sensors/window-2/shard-2/metadata-010.meta:0..38902], [fixtures/sensors/window-2/shard-3/metadata-011.meta:0..29412, fixtures/sensors/window-2/shard-3/metadata-012.meta:0..30476], [fixtures/sensors/window-2/shard-4/metadata-013.meta:0..37582]]}, projection=[key, @application, @device, @region, @station, @fleet], file_type=metadata, output_partitioning=Hash([Column { name: "key", index: 0 }], 4), max_parallel_files_per_partition=10
    │         t1: ConcurrentFileScanExec: file_groups={4 groups: [[fixtures/sensors/window-2/shard-5/metadata-014.meta:0..36879], [fixtures/sensors/window-2/shard-6/metadata-015.meta:0..38128], [fixtures/sensors/window-2/shard-7/metadata-016.meta:0..22837, fixtures/sensors/window-2/shard-7/metadata-017.meta:0..22791, fixtures/sensors/window-2/shard-7/metadata-018.meta:0..22677, fixtures/sensors/window-2/shard-7/metadata-019.meta:0..23007], [fixtures/sensors/window-2/shard-8/metadata-020.meta:0..20240, fixtures/sensors/window-2/shard-8/metadata-021.meta:0..19813, fixtures/sensors/window-2/shard-8/metadata-022.meta:0..19461, fixtures/sensors/window-2/shard-8/metadata-023.meta:0..20087, fixtures/sensors/window-2/shard-8/metadata-024.meta:0..19634]]}, projection=[key, @application, @device, @region, @station, @fleet], file_type=metadata, output_partitioning=Hash([Column { name: "key", index: 0 }], 4), max_parallel_files_per_partition=10
    │         t2: ConcurrentFileScanExec: file_groups={4 groups: [[fixtures/sensors/window-2/shard-9/metadata-025.meta:0..23851, fixtures/sensors/window-2/shard-9/metadata-026.meta:0..23550, fixtures/sensors/window-2/shard-9/metadata-027.meta:0..24401], [fixtures/sensors/window-2/shard-10/metadata-028.meta:0..28469, fixtures/sensors/window-2/shard-10/metadata-029.meta:0..28378], [fixtures/sensors/window-2/shard-11/metadata-030.meta:0..20920, fixtures/sensors/window-2/shard-11/metadata-031.meta:0..21858, fixtures/sensors/window-2/shard-11/metadata-032.meta:0..21427, fixtures/sensors/window-2/shard-11/metadata-033.meta:0..21461], [fixtures/sensors/window-2/shard-12/metadata-034.meta:0..37094]]}, projection=[key, @application, @device, @region, @station, @fleet], file_type=metadata, output_partitioning=Hash([Column { name: "key", index: 0 }], 4), max_parallel_files_per_partition=10
    │       BufferExec: capacity=_
    │         AggregateExec: mode=SinglePartitioned, gby=[key@0 as key, date_bin(Utf8("5 minutes"),SensorReadings.timestamp)@1 as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)], aggr=[], ordering_mode=Sorted
    │           ProjectionExec: expr=[key@0 as key, date_bin(IntervalMonthDayNano { months: 0, days: 0, nanoseconds: 300000000000 }, timestamp@1) as date_bin(Utf8("5 minutes"),SensorReadings.timestamp)]
    │             DistributedLeafExec:
    │               t0: ConcurrentFileScanExec: file_groups={4 groups: [[fixtures/sensors/window-2/shard-1/measurements-035.readings:0..8697], [fixtures/sensors/window-2/shard-2/measurements-036.readings:0..2941, fixtures/sensors/window-2/shard-2/measurements-037.readings:0..2727, fixtures/sensors/window-2/shard-2/measurements-038.readings:0..2680], [fixtures/sensors/window-2/shard-3/measurements-039.readings:0..6441], [fixtures/sensors/window-2/shard-4/measurements-040.readings:0..7382]]}, projection=[key, timestamp], output_ordering=[key@0 ASC, timestamp@1 ASC], file_type=measurements, output_partitioning=Hash([Column { name: "key", index: 0 }], 4), max_parallel_files_per_partition=10
    │               t1: ConcurrentFileScanExec: file_groups={4 groups: [[fixtures/sensors/window-2/shard-5/measurements-041.readings:0..6912], [fixtures/sensors/window-2/shard-6/measurements-042.readings:0..5703], [fixtures/sensors/window-2/shard-7/measurements-043.readings:0..6926], [fixtures/sensors/window-2/shard-8/measurements-044.readings:0..2829, fixtures/sensors/window-2/shard-8/measurements-045.readings:0..1792]]}, projection=[key, timestamp], output_ordering=[key@0 ASC, timestamp@1 ASC], file_type=measurements, output_partitioning=Hash([Column { name: "key", index: 0 }], 4), max_parallel_files_per_partition=10
    │               t2: ConcurrentFileScanExec: file_groups={4 groups: [[fixtures/sensors/window-2/shard-9/measurements-046.readings:0..5184], [fixtures/sensors/window-2/shard-10/measurements-047.readings:0..1201, fixtures/sensors/window-2/shard-10/measurements-048.readings:0..2065, fixtures/sensors/window-2/shard-10/measurements-049.readings:0..1327], [fixtures/sensors/window-2/shard-11/measurements-050.readings:0..1170, fixtures/sensors/window-2/shard-11/measurements-051.readings:0..2921, fixtures/sensors/window-2/shard-11/measurements-052.readings:0..2240], [fixtures/sensors/window-2/shard-12/measurements-053.readings:0..5231]]}, projection=[key, timestamp], output_ordering=[key@0 ASC, timestamp@1 ASC], file_type=measurements, output_partitioning=Hash([Column { name: "key", index: 0 }], 4), max_parallel_files_per_partition=10
    └──────────────────────────────────────────────────
