                  HashJoinExec: mode=CollectLeft, join_type=Inner, on=[(d_dkey@0, f_dkey@0)], projection=[service@1, f_dkey@2, timestamp@3, value@4]                                                                                                                                                                                                                                                                                                                             |

| physical_plan | ProjectionExec: expr=[f_dkey@0 as f_dkey, timestamp@1 as timestamp, value@3 as value]                                                                                                                                                                                                                                                                                                                                        |
|               |   SortMergeJoin: join_type=Inner, on=[(f_dkey@0, f_dkey@0)]                                                                                                                                                                                                                                                                                                                                                                  |
|               |     SortExec: expr=[f_dkey@0 ASC], preserve_partitioning=[true]                                                                                                                                                                                                                                                                                                                                                              |
|               |       CoalesceBatchesExec: target_batch_size=8192                                                                                                                                                                                                                                                                                                                                                                            |
|               |         RepartitionExec: partitioning=Hash([f_dkey@0], 4), input_partitions=3                                                                                                                                                                                                                                                                                                                                                |
|               |           DataSourceExec: file_groups={3 groups: [[f1.parquet], [f2.parquet], [f3.parquet]]}, projection=[f_dkey, timestamp], output_ordering=[f_dkey@0 ASC NULLS LAST, timestamp@1 ASC NULLS LAST], file_type=parquet |
|               |     SortExec: expr=[f_dkey@0 ASC], preserve_partitioning=[true]                                                                                                                                                                                                                                                                                                                                                              |
|               |       CoalesceBatchesExec: target_batch_size=8192                                                                                                                                                                                                                                                                                                                                                                            |
|               |         RepartitionExec: partitioning=Hash([f_dkey@0], 4), input_partitions=3                                                                                                                                                                                                                                                                                                                                                |
|               |           DataSourceExec: file_groups={3 groups: [[f1.parquet], [f2.parquet], [f3.parquet]]}, projection=[f_dkey, value], output_ordering=[f_dkey@0 ASC NULLS LAST], file_type=parquet                                 |
