 explain select f1.f_dkey, f1.timestamp, f2.value from   fact_parquet_sorted f1, fact_parquet_sorted f2  where f1.f_dkey = f2.f_dkey;
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                                                                                                                                                                                                                       |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: f1.f_dkey, f1.timestamp, f2.value                                                                                                                                                                                                                                                                                                                                                                              |
|               |   Inner Join: f1.f_dkey = f2.f_dkey                                                                                                                                                                                                                                                                                                                                                                                        |
|               |     SubqueryAlias: f1                                                                                                                                                                                                                                                                                                                                                                                                      |
|               |       TableScan: fact_parquet_sorted projection=[f_dkey, timestamp]                                                                                                                                                                                                                                                                                                                                                        |
|               |     SubqueryAlias: f2                                                                                                                                                                                                                                                                                                                                                                                                      |
|               |       TableScan: fact_parquet_sorted projection=[f_dkey, value]                                                                                                                                                                                                                                                                                                                                                            |
| physical_plan | ProjectionExec: expr=[f_dkey@0 as f_dkey, timestamp@1 as timestamp, value@3 as value]                                                                                                                                                                                                                                                                                                                                      |
|               |   SortMergeJoin: join_type=Inner, on=[(f_dkey@0, f_dkey@0)]                                                                                                                                                                                                                                                                                                                                                                |
|               |     CoalesceBatchesExec: target_batch_size=8192                                                                                                                                                                                                                                                                                                                                                                                |
|               |       RepartitionExec: partitioning=Hash([f_dkey@0], 4), input_partitions=3, preserve_order=true, sort_exprs=f_dkey@0 ASC NULLS LAST, timestamp@1 ASC NULLS LAST                                                                                                                                                                                                                                                           |
|               |         DataSourceExec: file_groups={3 groups: [[f1.parquet], [f2.parquet], [f3.parquet]]}, projection=[f_dkey, timestamp], output_ordering=[f_dkey@0 ASC NULLS LAST, timestamp@1 ASC NULLS LAST], file_type=parquet |
|               |     CoalesceBatchesExec: target_batch_size=8192                                                                                                                                                                                                                                                                                                                                                                            |
|               |       RepartitionExec: partitioning=Hash([f_dkey@0], 4), input_partitions=3, preserve_order=true, sort_exprs=f_dkey@0 ASC NULLS LAST                                                                                                                                                                                                                                                                                       |
|               |         DataSourceExec: file_groups={3 groups: [[f1.parquet], [f2.parquet], [f3.parquet]]}, projection=[f_dkey, value], output_ordering=[f_dkey@0 ASC NULLS LAST], file_type=parquet                                 |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                            |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
