ProjectionExec: expr=[f_dkey@1 as f_dkey, timestamp@2 as timestamp, value@3 as value, service@0 as service]                                                                                                                                                                                                                                                                                                                                                        |
  CoalesceBatchesExec: target_batch_size=8192                                                                                                                                                                                                                                                                                                                                                                                                                      |
    HashJoinExec: mode=CollectLeft, join_type=Inner, on=[(d_dkey@0, f_dkey@0)], projection=[service@1, f_dkey@2, timestamp@3, value@4]                                                                                                                                                                                                                                                                                                                             |
      CoalescePartitionsExec                                                                                                                                                                                                                                                                                                                                                                                                                                       |
        DataSourceExec: file_groups={2 groups: [[d1.parquet], [d2.parquet]]}, projection=[d_dkey, service], file_type=parquet                                                                                                                                                                              |
      UnionExec
            DataSourceExec: file_groups={1 group: [[f1.parquet]]}, projection=[id], projection=[f_dkey, timestamp, value], output_ordering=[f_dkey@0 ASC NULLS LAST, timestamp@1 ASC NULLS LAST], file_type=parquet
            SortExec: expr=[f_dkey@0 ASC NULLS LAST, timestamp@1 ASC NULLS LAST], preserve_partitioning=[false]
              DataSourceExec: file_groups={1 group: [[f2.parquet]]}, projection=[f_dkey, timestamp, value], file_type=parquet

  `
