EXPLAIN SELECT f.f_dkey, f.timestamp, f.value, d.service
FROM   dim2_parquet d, fact_parquet_sorted f
WHERE  d.d_dkey = f.f_dkey;
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: f.f_dkey, f.timestamp, f.value, d.service                                                                                                                                                                                                                                                                                                                                                                                                              |
|               |   Inner Join: d.d_dkey = f.f_dkey                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|               |     SubqueryAlias: d                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|               |       TableScan: dim2_parquet projection=[d_dkey, service]                                                                                                                                                                                                                                                                                                                                                                                                         |
|               |     SubqueryAlias: f                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|               |       TableScan: fact_parquet_sorted projection=[f_dkey, timestamp, value]                                                                                                                                                                                                                                                                                                                                                                                         |
| physical_plan | ProjectionExec: expr=[f_dkey@1 as f_dkey, timestamp@2 as timestamp, value@3 as value, service@0 as service]                                                                                                                                                                                                                                                                                                                                                        |
|               |   CoalesceBatchesExec: target_batch_size=8192                                                                                                                                                                                                                                                                                                                                                                                                                      |
|               |     HashJoinExec: mode=CollectLeft, join_type=Inner, on=[(d_dkey@0, f_dkey@0)], projection=[service@1, f_dkey@2, timestamp@3, value@4]                                                                                                                                                                                                                                                                                                                             |
|               |       CoalescePartitionsExec                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|               |         DataSourceExec: file_groups={2 groups: [[d1.parquet], [d2.parquet]]}, projection=[d_dkey, service], file_type=parquet                                                                                                                                                                              |
|               |       DataSourceExec: file_groups={3 groups: [[f1.parquet], [f2.parquet], [f3.parquet]]}, projection=[f_dkey, timestamp, value], output_ordering=[f_dkey@0 ASC NULLS LAST, timestamp@1 ASC NULLS LAST], file_type=parquet, predicate=DynamicFilter [ empty ] |
|               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
