import { ExcalidrawElement, ExcalidrawText } from '../../types/excalidraw.types';
import { NodeInfo } from '../types/node-info.types';
import { TextMeasurement } from './text-measurement';
import { arrowEndpoint, bindingAt } from './arrow-binding';

export interface LayoutRecord {
  info: NodeInfo;
  bodyId: string;
  own: ExcalidrawElement[];
  children: LayoutRecord[];
  headers: string[];
}

const measurement = new TextMeasurement();

/** Conservative width accommodates the supported operator and detail fonts. */
export function textWidth(text: string, size: number): number {
  return Math.max(measurement.measureText(text, size), text.length * size * 0.62);
}

/** Bound displayed text, including originalText, so editor restoration cannot undo wrapping. */
export function wrapLabel(text: string, width: number, size: number, maxLines = 6): string {
  const lines: string[] = [];
  for (const paragraph of text.split('\n')) {
    let remaining = paragraph.trim();
    while (textWidth(remaining, size) > width) {
      let end = 1;
      while (end < remaining.length && textWidth(remaining.slice(0, end + 1), size) <= width) end++;
      const prefix = remaining.slice(0, end);
      const boundary = Math.max(prefix.lastIndexOf(' '), prefix.lastIndexOf(',') + 1);
      if (boundary > end / 2) end = boundary;
      lines.push(remaining.slice(0, end).trimEnd());
      remaining = remaining.slice(end).trimStart();
    }
    lines.push(remaining);
  }
  if (lines.length > maxLines) {
    return [...lines.slice(0, maxLines - 1), lines[maxLines - 1].slice(0, -1) + '…'].join('\n');
  }
  return lines.join('\n');
}

function setText(element: ExcalidrawText, width: number, maxLines = 6): void {
  element.text = wrapLabel(element.text, width, element.fontSize, maxLines);
  element.originalText = element.text;
  element.width = width;
  element.height = element.text.split('\n').length * element.fontSize * element.lineHeight;
}

function descendants(record: LayoutRecord): ExcalidrawElement[] {
  return [...record.own, ...record.children.flatMap(descendants)];
}

function bounds(elements: ExcalidrawElement[]): { x: number; y: number; right: number; bottom: number } {
  const shapes = elements.filter((e) => e.type !== 'arrow');
  return {
    x: Math.min(...shapes.map((e) => e.x)),
    y: Math.min(...shapes.map((e) => e.y)),
    right: Math.max(...shapes.map((e) => e.x + e.width)),
    bottom: Math.max(...shapes.map((e) => e.y + e.height)),
  };
}

function move(elements: ExcalidrawElement[], dx: number, dy: number): void {
  for (const element of elements) {
    element.x += dx;
    element.y += dy;
  }
}

/** Fit owned contents before arranging complete child subtrees; reconnect edges last. */
export function layoutAdaptiveTree(
  root: LayoutRecord,
  elements: ExcalidrawElement[],
  verticalSpacing: number,
  horizontalSpacing: number
): void {
  const byId = new Map(elements.map((e) => [e.id, e]));
  const original = new Map(elements.map((e) => [e.id, { x: e.x, y: e.y, width: e.width, height: e.height }]));
  const records: LayoutRecord[] = [];
  const collect = (record: LayoutRecord): void => {
    records.push(record);
    record.children.forEach(collect);
  };
  collect(root);

  // Edge labels are generated by parents but travel and pack with their input subtree.
  for (const record of records) {
    for (const child of record.children) {
      const labels = record.own.filter((e) => e.type === 'text' &&
        e.groupIds.includes(child.info.groupId ?? '') && !e.containerId);
      child.own.push(...labels);
      record.own = record.own.filter((e) => !labels.includes(e));
    }
  }

  for (const record of records) {
    const body = byId.get(record.bodyId)!;
    const outer = byId.get(record.info.rectId)!;
    const oldBottom = body.y + body.height;
    const inBody = record.own.filter((e) => e !== body && e !== outer &&
      !record.headers.includes(e.id) && e.type !== 'arrow' &&
      e.y >= body.y && e.y < oldBottom &&
      e.x >= body.x - 1 && e.x + e.width <= body.x + body.width + 1);
    const glyphs = inBody.filter((e) => e.type !== 'text');
    const glyphLabels = new Map(glyphs.map((glyph) => [glyph.id, inBody.filter((e) => e.type === 'text' &&
      (e.containerId === glyph.id || (!e.containerId && e.x >= glyph.x && e.x < glyph.x + glyph.width &&
        e.y >= glyph.y && e.y < glyph.y + glyph.height)))]));
    const insideGlyph = new Set([...glyphLabels.values()].flat());
    const bodyText = inBody.filter((e): e is ExcalidrawText => e.type === 'text' &&
      !insideGlyph.has(e) && (!e.containerId || e.containerId === body.id));
    const width = Math.max(body.width, Math.min(520,
      Math.max(0, ...bodyText.map((e) => textWidth(e.text.split('\n')[0], e.fontSize))) + 24));
    body.width = width;
    let cursor = body.y + 8;
    for (const text of bodyText.sort((a, b) => a.y - b.y)) {
      setText(text, width - 24);
      text.x = body.x + 12;
      text.y = Math.max(cursor, text.y);
      cursor = text.y + text.height + 7;
    }
    // Glyph rows follow details. Bound labels follow their own glyph.
    if (glyphs.length) {
      const top = Math.min(...glyphs.map((e) => e.y));
      const delta = Math.max(0, cursor - top);
      for (const glyph of glyphs) {
        glyph.y += delta;
        const labels = glyphLabels.get(glyph.id) ?? [];
        const requiredWidth = Math.max(0, ...labels.filter((label): label is ExcalidrawText => label.type === 'text')
          .map((label) => Math.max(...label.text.split('\n').map((line) => textWidth(line, label.fontSize))) / 0.72));
        const newWidth = Math.min(body.width - 24, Math.max(glyph.width, requiredWidth));
        glyph.x -= (newWidth - glyph.width) / 2;
        glyph.width = newWidth;
        for (const label of glyphLabels.get(glyph.id) ?? []) {
          label.y += delta;
          if (label.type === 'text') {
            setText(label, glyph.width * 0.72, 2);
            label.x = glyph.x + (glyph.width - label.width) / 2;
            label.y = glyph.y + (glyph.height - label.height) / 2;
          }
        }
      }
      cursor = Math.max(cursor, ...glyphs.map((e) => e.y + e.height + 12));
    }
    body.height = Math.max(body.height, cursor - body.y);
    const delta = body.y + body.height - oldBottom;
    for (const e of record.own) {
      if (e.type !== 'arrow' && e !== outer && e !== body && e.y >= oldBottom && !inBody.includes(e)) {
        e.y += delta;
      }
    }
    outer.width = body.width;
    if (outer !== body) outer.height = body.y + body.height - outer.y;
    for (const headerId of record.headers) {
      const header = byId.get(headerId)!;
      header.x = outer.x;
      header.width = outer.width;
      for (const e of record.own) {
        if (e.type === 'text' && e.containerId === headerId) {
          e.x = header.x + 12;
          e.width = header.width - 24;
        }
      }
    }
    // Outside labels are bounded too; include them in subtree occupied bounds.
    for (const e of record.own) {
      if (e.type === 'text' && !inBody.includes(e) && !e.containerId) {
        setText(e, Math.min(300, Math.max(e.width, textWidth(e.text, e.fontSize))), 4);
      }
    }
  }

  // Wrapped edge labels must finish above the child box, not cross its title.
  for (const record of records) {
    const outer = byId.get(record.info.rectId)!;
    const labels = record.own.filter((e) => e.type === 'text' && !e.containerId && e.y < outer.y &&
      e.groupIds.includes(record.info.groupId ?? ''));
    if (labels.length) {
      const bottom = Math.max(...labels.map((e) => e.y + e.height));
      move(labels, 0, Math.min(0, outer.y - 20 - bottom));
    }
  }

  const arrange = (record: LayoutRecord): void => {
    record.children.forEach(arrange);
    const outer = byId.get(record.info.rectId)!;
    const children = record.children;
    if (!children.length) return;
    const areas = children.map((child) => bounds(descendants(child)));
    const width = areas.reduce((sum, b) => sum + b.right - b.x, 0) +
      horizontalSpacing * (children.length - 1);
    let left = outer.x + outer.width / 2 - width / 2;
    const ownBottom = bounds(record.own).bottom;
    children.forEach((child, i) => {
      const area = areas[i];
      const targetY = ownBottom + Math.max(verticalSpacing, 70);
      // Unary chains share a box centerline. File glyphs and edge labels can
      // make occupied bounds asymmetric; those bounds only control sibling packing.
      const childBox = byId.get(child.info.rectId)!;
      const dx = children.length === 1 ?
        outer.x + outer.width / 2 - (childBox.x + childBox.width / 2) :
        left - area.x;
      move(descendants(child), dx, targetY - area.y);
      left += area.right - area.x + horizontalSpacing;
    });
  };
  arrange(root);

  // Bind to the same relative port on each moved/resized shape.
  for (const e of elements) {
    if (e.type !== 'arrow') continue;
    const start = arrowEndpoint({ ...e, ...original.get(e.id)! }, 'start');
    const end = arrowEndpoint({ ...e, ...original.get(e.id)! }, 'end');
    const transform = (id: string | undefined, point: { x: number; y: number }): { x: number; y: number } => {
      const before = id ? original.get(id) : undefined;
      const after = id ? byId.get(id) : undefined;
      if (!before || !after) return point;
      return {
        x: after.x + (point.x - before.x) / (before.width || 1) * after.width,
        y: after.y + (point.y - before.y) / (before.height || 1) * after.height,
      };
    };
    const a = transform(e.startBinding?.elementId, start);
    const b = transform(e.endBinding?.elementId, end);
    e.x = a.x;
    e.y = a.y;
    e.points = [[0, 0], [b.x - a.x, b.y - a.y]];
    e.width = Math.abs(b.x - a.x);
    e.height = Math.abs(b.y - a.y);
    if (e.startBinding) e.startBinding = bindingAt(byId.get(e.startBinding.elementId)!, a.x, a.y, b.x, b.y);
    if (e.endBinding) e.endBinding = bindingAt(byId.get(e.endBinding.elementId)!, b.x, b.y, a.x, a.y);
  }
}

/** Generated expression-shaped names are summarized only for display, never for metadata. */
export function compactExpression(text: string): string {
  if (text.length <= 60) return text;
  const functionName = text.match(/^([A-Za-z_]\w*)\s*\(/);
  return functionName ? functionName[1] + '(…)' : text;
}
